### PR TITLE
Added support for koa@2

### PR DESCRIPTION
**Pull request by kripod**

### CODE REVIEW

**Comment by mpint** [comment]
+1

**Comment by davezuko** [comment]
Sorry totally didn't see this, will merge when I get home!

**Comment by mpint** [comment]
@kripod, this is off topic, but if you have one, could you post a working example of this module in a single page app?  I'm having an awful time getting it working.  Would be greatly appreciated!

**Comment by davezuko** [comment]
@mpint https://github.com/davezuko/react-redux-starter-kit/blob/master/server/main.js#L25

**Comment by mpint** [comment]
thanks @davezuko!

**Comment by kripod** [comment]
Thanks for merging! :)

**Pull request merged**
